### Lets import the library

In [1]:
# To convert our output into csv
import pandas as pd

# To scrape the data from website
from bs4 import BeautifulSoup

# To get a https request from websites
import requests
from requests import get

In [2]:
url = 'https://www.flipkart.com/search?q=mobile+under+50000+rs&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=on&as=off'
# Empty List
pro_name = []
pro_price = []
pro_rating = []

In [3]:
for i in range(1,355):  # Adjust the range as per the actual number of pages available
    page_url = f'{url}&page={i}'
    r = requests.get(page_url)
    soup = BeautifulSoup(r.text, 'html.parser')
    master_container = soup.find_all('div', {'class': '_2kHMtA'})    
    
    if not master_container:
        break  # Break the loop if there is no data on the page

    for j in master_container:
        name = j.find('div', {'class': '_4rR01T'})
        price = j.find('div', {'class': '_30jeq3 _1_WHN1'})
        rating = j.find('div', {'class': '_3LWZlK'})

        if name and price:  # Check if name and price elements are found
            pro_name.append(name.text.strip())
            pro_price.append(price.text.strip())
        else:
            # If name or price is not found, we skip this entry
            continue

        if rating:
            pro_rating.append(rating.text.strip())
        else:
            pro_rating.append("NA")

In [4]:
# Create the DataFrame
df = pd.DataFrame({"Product Name": pro_name, "Product Price": pro_price, "Product Rating": pro_rating})
df

,Product Name,Product Price,Product Rating
0,"SAMSUNG Galaxy S22 Plus 5G (Phantom Black, 128...","₹49,999",4.5
1,"SAMSUNG Galaxy Z Flip3 5G (Phantom Black, 128 GB)","₹44,999",4.3
2,"MOTOROLA Edge 30 Ultra (Interstellar Black, 25...","₹49,999",4.3
3,"MOTOROLA Edge 30 Ultra (Starlight White, 256 GB)","₹49,999",4.3
4,"Google Pixel 7 (Snow, 128 GB)","₹47,999",4.4
...,...,...,...
978,I Kall K3310,₹744,3.6
979,"vivo Y75 (Dancing waves, 128 GB)","₹19,990",4.3
980,"REDMI Note 11S (Horizon Blue, 64 GB)","₹13,990",4.1
981,Kechaoda THE KING OF MUSIC,"₹1,499",3.9
982,"Infinix Note 12 Pro (Tuscany Blue, 256 GB)","₹16,999",4.2

In [59]:
# df.to_csv("smc")

# THE END